export const TODO_ACTION_CONST = {
  CREATE_TODO: "CREATE_TODO",
  SEND_EACH_SELECTED_ID: "SEND_EACH_SELECTED_ID",
  SEND_ALL_SELECTED_ID: "SEND_ALL_SELECTED_ID",
  MARK_AS_DONE: "MARK_AS_DONE",
  MARK_AS_NOT_DONE: "MARK_AS_NOT_DONE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
};
